//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KojtoCAD.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KojtoCAD")]
        public string appName {
            get {
                return ((string)(this["appName"]));
            }
            set {
                this["appName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastSelectedManufacturer {
            get {
                return ((string)(this["lastSelectedManufacturer"]));
            }
            set {
                this["lastSelectedManufacturer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastSelectedSearchPattern {
            get {
                return ((string)(this["lastSelectedSearchPattern"]));
            }
            set {
                this["lastSelectedSearchPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastSelectedProject {
            get {
                return ((string)(this["lastSelectedProject"]));
            }
            set {
                this["lastSelectedProject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastSelectedPaperSize {
            get {
                return ((string)(this["lastSelectedPaperSize"]));
            }
            set {
                this["lastSelectedPaperSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastSelectedPaperOrientation {
            get {
                return ((string)(this["lastSelectedPaperOrientation"]));
            }
            set {
                this["lastSelectedPaperOrientation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastSelectedTitleBlock {
            get {
                return ((string)(this["lastSelectedTitleBlock"]));
            }
            set {
                this["lastSelectedTitleBlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.7\\data\\KojtoCAD\\Symbols\\")]
        public string FileServer {
            get {
                return ((string)(this["FileServer"]));
            }
            set {
                this["FileServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SPG_HasDimensions {
            get {
                return ((bool)(this["SPG_HasDimensions"]));
            }
            set {
                this["SPG_HasDimensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SPG_MaterialSide {
            get {
                return ((int)(this["SPG_MaterialSide"]));
            }
            set {
                this["SPG_MaterialSide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SPG_CoatingSide {
            get {
                return ((int)(this["SPG_CoatingSide"]));
            }
            set {
                this["SPG_CoatingSide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal SPG_Thickness {
            get {
                return ((decimal)(this["SPG_Thickness"]));
            }
            set {
                this["SPG_Thickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal SPG_InternalRadius {
            get {
                return ((decimal)(this["SPG_InternalRadius"]));
            }
            set {
                this["SPG_InternalRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SPG_HasCoating {
            get {
                return ((bool)(this["SPG_HasCoating"]));
            }
            set {
                this["SPG_HasCoating"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SPG_MaterialLayer {
            get {
                return ((string)(this["SPG_MaterialLayer"]));
            }
            set {
                this["SPG_MaterialLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color SPG_MaterialColor {
            get {
                return ((global::System.Drawing.Color)(this["SPG_MaterialColor"]));
            }
            set {
                this["SPG_MaterialColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SPG_CoatingLayer {
            get {
                return ((string)(this["SPG_CoatingLayer"]));
            }
            set {
                this["SPG_CoatingLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color SPG_CoatingColor {
            get {
                return ((global::System.Drawing.Color)(this["SPG_CoatingColor"]));
            }
            set {
                this["SPG_CoatingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SPG_DimensionLayer {
            get {
                return ((string)(this["SPG_DimensionLayer"]));
            }
            set {
                this["SPG_DimensionLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SPG_DimensionStyle {
            get {
                return ((string)(this["SPG_DimensionStyle"]));
            }
            set {
                this["SPG_DimensionStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ArcsAndLines")]
        public string SPG_DimensionStandart {
            get {
                return ((string)(this["SPG_DimensionStandart"]));
            }
            set {
                this["SPG_DimensionStandart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color SPG_DimensionColor {
            get {
                return ((global::System.Drawing.Color)(this["SPG_DimensionColor"]));
            }
            set {
                this["SPG_DimensionColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool U2D_ThicknessIsPredefined {
            get {
                return ((bool)(this["U2D_ThicknessIsPredefined"]));
            }
            set {
                this["U2D_ThicknessIsPredefined"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool U2D_InternalRadiusIsPredefined {
            get {
                return ((bool)(this["U2D_InternalRadiusIsPredefined"]));
            }
            set {
                this["U2D_InternalRadiusIsPredefined"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool U2D_MethodIsBendDeduction {
            get {
                return ((bool)(this["U2D_MethodIsBendDeduction"]));
            }
            set {
                this["U2D_MethodIsBendDeduction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool U2D_MethodIsKFactor {
            get {
                return ((bool)(this["U2D_MethodIsKFactor"]));
            }
            set {
                this["U2D_MethodIsKFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string U2D_BendDeductionTableFile {
            get {
                return ((string)(this["U2D_BendDeductionTableFile"]));
            }
            set {
                this["U2D_BendDeductionTableFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string U2D_KFactorTableFile {
            get {
                return ((string)(this["U2D_KFactorTableFile"]));
            }
            set {
                this["U2D_KFactorTableFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool U2D_KFactorIsPredefined {
            get {
                return ((bool)(this["U2D_KFactorIsPredefined"]));
            }
            set {
                this["U2D_KFactorIsPredefined"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool U2D_DrawCoating {
            get {
                return ((bool)(this["U2D_DrawCoating"]));
            }
            set {
                this["U2D_DrawCoating"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color U2D_CoatingColor {
            get {
                return ((global::System.Drawing.Color)(this["U2D_CoatingColor"]));
            }
            set {
                this["U2D_CoatingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string U2D_CoatingLayer {
            get {
                return ((string)(this["U2D_CoatingLayer"]));
            }
            set {
                this["U2D_CoatingLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool U2D_DrawDimensions {
            get {
                return ((bool)(this["U2D_DrawDimensions"]));
            }
            set {
                this["U2D_DrawDimensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string U2D_DimensionStyle {
            get {
                return ((string)(this["U2D_DimensionStyle"]));
            }
            set {
                this["U2D_DimensionStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color U2D_DimensionColor {
            get {
                return ((global::System.Drawing.Color)(this["U2D_DimensionColor"]));
            }
            set {
                this["U2D_DimensionColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string U2D_DimensionLayer {
            get {
                return ((string)(this["U2D_DimensionLayer"]));
            }
            set {
                this["U2D_DimensionLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ArcsAndLines")]
        public string U2D_DimensionStandart {
            get {
                return ((string)(this["U2D_DimensionStandart"]));
            }
            set {
                this["U2D_DimensionStandart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int U2D_CoatingSide {
            get {
                return ((int)(this["U2D_CoatingSide"]));
            }
            set {
                this["U2D_CoatingSide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public decimal U2D_KFactor {
            get {
                return ((decimal)(this["U2D_KFactor"]));
            }
            set {
                this["U2D_KFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal U2D_Thickness {
            get {
                return ((decimal)(this["U2D_Thickness"]));
            }
            set {
                this["U2D_Thickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal U2D_InternalRadius {
            get {
                return ((decimal)(this["U2D_InternalRadius"]));
            }
            set {
                this["U2D_InternalRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SGU_IsLaminated {
            get {
                return ((bool)(this["SGU_IsLaminated"]));
            }
            set {
                this["SGU_IsLaminated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal SGU_GlassThickness {
            get {
                return ((decimal)(this["SGU_GlassThickness"]));
            }
            set {
                this["SGU_GlassThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal SGU_InnerGlassThickness {
            get {
                return ((decimal)(this["SGU_InnerGlassThickness"]));
            }
            set {
                this["SGU_InnerGlassThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal SGU_OuterGlassThickness {
            get {
                return ((decimal)(this["SGU_OuterGlassThickness"]));
            }
            set {
                this["SGU_OuterGlassThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal SGU_ProfileLenght {
            get {
                return ((decimal)(this["SGU_ProfileLenght"]));
            }
            set {
                this["SGU_ProfileLenght"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.38")]
        public decimal SGU_PVBThickness {
            get {
                return ((decimal)(this["SGU_PVBThickness"]));
            }
            set {
                this["SGU_PVBThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DGU_InnerGlassIsLaminated {
            get {
                return ((bool)(this["DGU_InnerGlassIsLaminated"]));
            }
            set {
                this["DGU_InnerGlassIsLaminated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal DGU_InnerGlassThickness {
            get {
                return ((decimal)(this["DGU_InnerGlassThickness"]));
            }
            set {
                this["DGU_InnerGlassThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal DGU_InnerInternalGlassThickness {
            get {
                return ((decimal)(this["DGU_InnerInternalGlassThickness"]));
            }
            set {
                this["DGU_InnerInternalGlassThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal DGU_InnerExternalGlassThickness {
            get {
                return ((decimal)(this["DGU_InnerExternalGlassThickness"]));
            }
            set {
                this["DGU_InnerExternalGlassThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal DGU_InnerPVBThickness {
            get {
                return ((decimal)(this["DGU_InnerPVBThickness"]));
            }
            set {
                this["DGU_InnerPVBThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal DGU_OuterGlassThickness {
            get {
                return ((decimal)(this["DGU_OuterGlassThickness"]));
            }
            set {
                this["DGU_OuterGlassThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal DGU_OuterExternalGlassThickness {
            get {
                return ((decimal)(this["DGU_OuterExternalGlassThickness"]));
            }
            set {
                this["DGU_OuterExternalGlassThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal DGU_OuterInternalGlassThickness {
            get {
                return ((decimal)(this["DGU_OuterInternalGlassThickness"]));
            }
            set {
                this["DGU_OuterInternalGlassThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal DGU_OuterPVBThickness {
            get {
                return ((decimal)(this["DGU_OuterPVBThickness"]));
            }
            set {
                this["DGU_OuterPVBThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DGU_InnerGlassHasFoil {
            get {
                return ((bool)(this["DGU_InnerGlassHasFoil"]));
            }
            set {
                this["DGU_InnerGlassHasFoil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DGU_OuterGlassHasFoil {
            get {
                return ((bool)(this["DGU_OuterGlassHasFoil"]));
            }
            set {
                this["DGU_OuterGlassHasFoil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal DGU_ProfileLenght {
            get {
                return ((decimal)(this["DGU_ProfileLenght"]));
            }
            set {
                this["DGU_ProfileLenght"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DGU_OuterGlassIsLaminated {
            get {
                return ((bool)(this["DGU_OuterGlassIsLaminated"]));
            }
            set {
                this["DGU_OuterGlassIsLaminated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal DGU_GapThickness {
            get {
                return ((decimal)(this["DGU_GapThickness"]));
            }
            set {
                this["DGU_GapThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TGU_InnerGlassIsLaminated {
            get {
                return ((bool)(this["TGU_InnerGlassIsLaminated"]));
            }
            set {
                this["TGU_InnerGlassIsLaminated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal TGU_InnerGlassThickness {
            get {
                return ((decimal)(this["TGU_InnerGlassThickness"]));
            }
            set {
                this["TGU_InnerGlassThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal TGU_InnerInternalGlassThickness {
            get {
                return ((decimal)(this["TGU_InnerInternalGlassThickness"]));
            }
            set {
                this["TGU_InnerInternalGlassThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal TGU_InnerExternalGlassThickness {
            get {
                return ((decimal)(this["TGU_InnerExternalGlassThickness"]));
            }
            set {
                this["TGU_InnerExternalGlassThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal TGU_InnerPVBThickness {
            get {
                return ((decimal)(this["TGU_InnerPVBThickness"]));
            }
            set {
                this["TGU_InnerPVBThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TGU_InnerGlassHasFoil {
            get {
                return ((bool)(this["TGU_InnerGlassHasFoil"]));
            }
            set {
                this["TGU_InnerGlassHasFoil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TGU_OuterGlassIsLaminated {
            get {
                return ((bool)(this["TGU_OuterGlassIsLaminated"]));
            }
            set {
                this["TGU_OuterGlassIsLaminated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal TGU_OuterGlassThickness {
            get {
                return ((decimal)(this["TGU_OuterGlassThickness"]));
            }
            set {
                this["TGU_OuterGlassThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal TGU_OuterInternalGlassThickness {
            get {
                return ((decimal)(this["TGU_OuterInternalGlassThickness"]));
            }
            set {
                this["TGU_OuterInternalGlassThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal TGU_OuterExternalGlassThickness {
            get {
                return ((decimal)(this["TGU_OuterExternalGlassThickness"]));
            }
            set {
                this["TGU_OuterExternalGlassThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal TGU_OuterPVBThickness {
            get {
                return ((decimal)(this["TGU_OuterPVBThickness"]));
            }
            set {
                this["TGU_OuterPVBThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TGU_OuterGlassHasFoil {
            get {
                return ((bool)(this["TGU_OuterGlassHasFoil"]));
            }
            set {
                this["TGU_OuterGlassHasFoil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal TGU_InnerGapThickness {
            get {
                return ((decimal)(this["TGU_InnerGapThickness"]));
            }
            set {
                this["TGU_InnerGapThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal TGU_OuterGapThickness {
            get {
                return ((decimal)(this["TGU_OuterGapThickness"]));
            }
            set {
                this["TGU_OuterGapThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal TGU_MiddleGlassThickness {
            get {
                return ((decimal)(this["TGU_MiddleGlassThickness"]));
            }
            set {
                this["TGU_MiddleGlassThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal TGU_ProfileLenght {
            get {
                return ((decimal)(this["TGU_ProfileLenght"]));
            }
            set {
                this["TGU_ProfileLenght"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SHD_Material {
            get {
                return ((string)(this["SHD_Material"]));
            }
            set {
                this["SHD_Material"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SHD_HasCoating {
            get {
                return ((bool)(this["SHD_HasCoating"]));
            }
            set {
                this["SHD_HasCoating"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1-0")]
        public string SHD_CoatingLayer {
            get {
                return ((string)(this["SHD_CoatingLayer"]));
            }
            set {
                this["SHD_CoatingLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color SHD_CoatingColor {
            get {
                return ((global::System.Drawing.Color)(this["SHD_CoatingColor"]));
            }
            set {
                this["SHD_CoatingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SHD_CoatingSide {
            get {
                return ((int)(this["SHD_CoatingSide"]));
            }
            set {
                this["SHD_CoatingSide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RInsulationThicknessAtFirstPoint {
            get {
                return ((double)(this["RInsulationThicknessAtFirstPoint"]));
            }
            set {
                this["RInsulationThicknessAtFirstPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RInsulationThicknessAtSecondPoint {
            get {
                return ((double)(this["RInsulationThicknessAtSecondPoint"]));
            }
            set {
                this["RInsulationThicknessAtSecondPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HelpLineOffset {
            get {
                return ((double)(this["HelpLineOffset"]));
            }
            set {
                this["HelpLineOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WeldingArcsLenght {
            get {
                return ((double)(this["WeldingArcsLenght"]));
            }
            set {
                this["WeldingArcsLenght"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WeldingArcsDistance {
            get {
                return ((double)(this["WeldingArcsDistance"]));
            }
            set {
                this["WeldingArcsDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SlottedHoleLength {
            get {
                return ((double)(this["SlottedHoleLength"]));
            }
            set {
                this["SlottedHoleLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SlottedHoleDiameter {
            get {
                return ((double)(this["SlottedHoleDiameter"]));
            }
            set {
                this["SlottedHoleDiameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SlottedHoleRotationAngle {
            get {
                return ((double)(this["SlottedHoleRotationAngle"]));
            }
            set {
                this["SlottedHoleRotationAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal GearNumberOfTheeth {
            get {
                return ((decimal)(this["GearNumberOfTheeth"]));
            }
            set {
                this["GearNumberOfTheeth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal GearModule {
            get {
                return ((decimal)(this["GearModule"]));
            }
            set {
                this["GearModule"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TitleMarkLenght {
            get {
                return ((double)(this["TitleMarkLenght"]));
            }
            set {
                this["TitleMarkLenght"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SInsulationThicknessAtFirstPoint {
            get {
                return ((double)(this["SInsulationThicknessAtFirstPoint"]));
            }
            set {
                this["SInsulationThicknessAtFirstPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SInsulationThicknessAtSecondPoint {
            get {
                return ((double)(this["SInsulationThicknessAtSecondPoint"]));
            }
            set {
                this["SInsulationThicknessAtSecondPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HInsulationThickness {
            get {
                return ((double)(this["HInsulationThickness"]));
            }
            set {
                this["HInsulationThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HInsulationInternalRadius {
            get {
                return ((double)(this["HInsulationInternalRadius"]));
            }
            set {
                this["HInsulationInternalRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HInsulationSegmentLenght {
            get {
                return ((double)(this["HInsulationSegmentLenght"]));
            }
            set {
                this["HInsulationSegmentLenght"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RegionDescrDensity {
            get {
                return ((double)(this["RegionDescrDensity"]));
            }
            set {
                this["RegionDescrDensity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string plotSourcePath {
            get {
                return ((string)(this["plotSourcePath"]));
            }
            set {
                this["plotSourcePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plotDevicePdf {
            get {
                return ((string)(this["plotDevicePdf"]));
            }
            set {
                this["plotDevicePdf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plotDeviceDwf {
            get {
                return ((string)(this["plotDeviceDwf"]));
            }
            set {
                this["plotDeviceDwf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plotDevicePrinter {
            get {
                return ((string)(this["plotDevicePrinter"]));
            }
            set {
                this["plotDevicePrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plotPaperSizePrint {
            get {
                return ((string)(this["plotPaperSizePrint"]));
            }
            set {
                this["plotPaperSizePrint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plotPaperSizePdf {
            get {
                return ((string)(this["plotPaperSizePdf"]));
            }
            set {
                this["plotPaperSizePdf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plotPaperSizeDwf {
            get {
                return ((string)(this["plotPaperSizeDwf"]));
            }
            set {
                this["plotPaperSizeDwf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plotStyleTable {
            get {
                return ((string)(this["plotStyleTable"]));
            }
            set {
                this["plotStyleTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plotReadDwg {
            get {
                return ((bool)(this["plotReadDwg"]));
            }
            set {
                this["plotReadDwg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plotReadDxf {
            get {
                return ((bool)(this["plotReadDxf"]));
            }
            set {
                this["plotReadDxf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plotMakePrint {
            get {
                return ((bool)(this["plotMakePrint"]));
            }
            set {
                this["plotMakePrint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plotMakePdf {
            get {
                return ((bool)(this["plotMakePdf"]));
            }
            set {
                this["plotMakePdf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plotMakeDwf {
            get {
                return ((bool)(this["plotMakeDwf"]));
            }
            set {
                this["plotMakeDwf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plotSavePath {
            get {
                return ((string)(this["plotSavePath"]));
            }
            set {
                this["plotSavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plotIgnoreModelSpace {
            get {
                return ((bool)(this["plotIgnoreModelSpace"]));
            }
            set {
                this["plotIgnoreModelSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plotPlotAllDWGs {
            get {
                return ((bool)(this["plotPlotAllDWGs"]));
            }
            set {
                this["plotPlotAllDWGs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plotMultiSheet {
            get {
                return ((bool)(this["plotMultiSheet"]));
            }
            set {
                this["plotMultiSheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plotDrawingFrameLayer {
            get {
                return ((string)(this["plotDrawingFrameLayer"]));
            }
            set {
                this["plotDrawingFrameLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plotDrawingFrameName {
            get {
                return ((string)(this["plotDrawingFrameName"]));
            }
            set {
                this["plotDrawingFrameName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plotTurnOnViewPorts {
            get {
                return ((bool)(this["plotTurnOnViewPorts"]));
            }
            set {
                this["plotTurnOnViewPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plotFitToPage {
            get {
                return ((bool)(this["plotFitToPage"]));
            }
            set {
                this["plotFitToPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plotCenterPlot {
            get {
                return ((bool)(this["plotCenterPlot"]));
            }
            set {
                this["plotCenterPlot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Files\\Templates\\")]
        public string templatesDir {
            get {
                return ((string)(this["templatesDir"]));
            }
            set {
                this["templatesDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Files\\Icons\\")]
        public string iconsDir {
            get {
                return ((string)(this["iconsDir"]));
            }
            set {
                this["iconsDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Files\\Lisp\\")]
        public string lispDir {
            get {
                return ((string)(this["lispDir"]));
            }
            set {
                this["lispDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Files\\Dynamic_blocks\\")]
        public string dynamicBlocksDir {
            get {
                return ((string)(this["dynamicBlocksDir"]));
            }
            set {
                this["dynamicBlocksDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string attChecker_excelFile {
            get {
                return ((string)(this["attChecker_excelFile"]));
            }
            set {
                this["attChecker_excelFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string attChecker_logFile {
            get {
                return ((string)(this["attChecker_logFile"]));
            }
            set {
                this["attChecker_logFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool attChecker_traverseAllFiles {
            get {
                return ((bool)(this["attChecker_traverseAllFiles"]));
            }
            set {
                this["attChecker_traverseAllFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string attChecker_selectedSheet {
            get {
                return ((string)(this["attChecker_selectedSheet"]));
            }
            set {
                this["attChecker_selectedSheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string attChecker_existingAttributeColor {
            get {
                return ((string)(this["attChecker_existingAttributeColor"]));
            }
            set {
                this["attChecker_existingAttributeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string attChecker_unExistingAttributeColor {
            get {
                return ((string)(this["attChecker_unExistingAttributeColor"]));
            }
            set {
                this["attChecker_unExistingAttributeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string attChecker_selecetdBlock {
            get {
                return ((string)(this["attChecker_selecetdBlock"]));
            }
            set {
                this["attChecker_selecetdBlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string attChecker_selectedAttribute {
            get {
                return ((string)(this["attChecker_selectedAttribute"]));
            }
            set {
                this["attChecker_selectedAttribute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool attChecker_isRealNumber {
            get {
                return ((bool)(this["attChecker_isRealNumber"]));
            }
            set {
                this["attChecker_isRealNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool attChecker_hasCommaDelimiter {
            get {
                return ((bool)(this["attChecker_hasCommaDelimiter"]));
            }
            set {
                this["attChecker_hasCommaDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool attChecker_hasPointDelimiter {
            get {
                return ((bool)(this["attChecker_hasPointDelimiter"]));
            }
            set {
                this["attChecker_hasPointDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4-0")]
        public string weldingLineLayer {
            get {
                return ((string)(this["weldingLineLayer"]));
            }
            set {
                this["weldingLineLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color weldingLineLayerColor {
            get {
                return ((global::System.Drawing.Color)(this["weldingLineLayerColor"]));
            }
            set {
                this["weldingLineLayerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Files\\Tables\\")]
        public string tablesDir {
            get {
                return ((string)(this["tablesDir"]));
            }
            set {
                this["tablesDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KojtoCAD.bundle")]
        public string appDir {
            get {
                return ((string)(this["appDir"]));
            }
            set {
                this["appDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plotTransparency {
            get {
                return ((bool)(this["plotTransparency"]));
            }
            set {
                this["plotTransparency"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kojtocad")]
        public string BlobContainerName {
            get {
                return ((string)(this["BlobContainerName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=3dsoft;AccountKey=hzHT/Lb9lrCvFBkdVxVi" +
            "9in1ZVePQnRCNltTbBDq34Wocle8+S//doo5nY1Kkr5zdg+XxX42OHgTImcCyrFtig==")]
        public string BlobConnectionString {
            get {
                return ((string)(this["BlobConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InstallVersions")]
        public string NewVersionsVirtualDirectory {
            get {
                return ((string)(this["NewVersionsVirtualDirectory"]));
            }
        }
    }
}
