//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KojtoCAD.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KojtoCAD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ba {
            get {
                object obj = ResourceManager.GetObject("ba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banner_prototyp_750x300px_var2 {
            get {
                object obj = ResourceManager.GetObject("banner_prototyp_750x300px_var2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bd {
            get {
                object obj = ResourceManager.GetObject("bd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating toolbar button..
        /// </summary>
        internal static string ErrorCreatingToolbarButton {
            get {
                return ResourceManager.GetString("ErrorCreatingToolbarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating the UI. KojtoCAD is loaded but with no UI..
        /// </summary>
        internal static string ErrorCreatingUi {
            get {
                return ResourceManager.GetString("ErrorCreatingUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create UI directory. UI will not be created..
        /// </summary>
        internal static string ErrorCreatingUiDirectory {
            get {
                return ResourceManager.GetString("ErrorCreatingUiDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuold not delete icon..
        /// </summary>
        internal static string ErrorDeletingIcon {
            get {
                return ResourceManager.GetString("ErrorDeletingIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting icon..
        /// </summary>
        internal static string ErrorGettingIcon {
            get {
                return ResourceManager.GetString("ErrorGettingIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons directory does not exist..
        /// </summary>
        internal static string ErrorIconsDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorIconsDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        internal static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UiGenerator started..
        /// </summary>
        internal static string InfoUiGenerationStarted {
            get {
                return ResourceManager.GetString("InfoUiGenerationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kf {
            get {
                object obj = ResourceManager.GetObject("kf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KojtoCad Plotter.
        /// </summary>
        internal static string KojtoCadPlotter {
            get {
                return ResourceManager.GetString("KojtoCadPlotter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi sheet PDF with different frame format is not allowed. If your drawings have different frames press Cancel and separate them by frame..
        /// </summary>
        internal static string MultiSheetWithDifferentFramesWarning {
            get {
                return ResourceManager.GetString("MultiSheetWithDifferentFramesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select bend deduction table..
        /// </summary>
        internal static string PickUpBendDeductionTable {
            get {
                return ResourceManager.GetString("PickUpBendDeductionTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Prototyp {
            get {
                object obj = ResourceManager.GetObject("Prototyp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real print confirmation.
        /// </summary>
        internal static string RealPrintConfirmation {
            get {
                return ResourceManager.GetString("RealPrintConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you REALLY shure you want to PRINT TO PAPER ALL these DWGs ? If otherwise click NO, unckeck &apos;Print&apos; option and try again..
        /// </summary>
        internal static string RealPrintWarning {
            get {
                return ResourceManager.GetString("RealPrintWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set K-Factor..
        /// </summary>
        internal static string SetKFactor {
            get {
                return ResourceManager.GetString("SetKFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KojtoCAD UI generated successfully..
        /// </summary>
        internal static string SuccessCreatingUi {
            get {
                return ResourceManager.GetString("SuccessCreatingUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user interface generator works with AutoCAD 2007 and above..
        /// </summary>
        internal static string WarningUiVersion {
            get {
                return ResourceManager.GetString("WarningUiVersion", resourceCulture);
            }
        }
    }
}
