//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KojtoCAD.UnitTests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BLAAAAAAAAA")]
        public string nonexistingRootDirectory {
            get {
                return ((string)(this["nonexistingRootDirectory"]));
            }
            set {
                this["nonexistingRootDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BLAAAAAA!")]
        public string nonexistingFileNamePart {
            get {
                return ((string)(this["nonexistingFileNamePart"]));
            }
            set {
                this["nonexistingFileNamePart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string nullFileExtension {
            get {
                return ((string)(this["nullFileExtension"]));
            }
            set {
                this["nullFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool falseTraverseSubdirectories {
            get {
                return ((bool)(this["falseTraverseSubdirectories"]));
            }
            set {
                this["falseTraverseSubdirectories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\IFileService.TestFiles")]
        public string existingRootDirectorty {
            get {
                return ((string)(this["existingRootDirectorty"]));
            }
            set {
                this["existingRootDirectorty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("windows")]
        public string singleFileNamePart {
            get {
                return ((string)(this["singleFileNamePart"]));
            }
            set {
                this["singleFileNamePart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Angel")]
        public string multipleFileNamePart {
            get {
                return ((string)(this["multipleFileNamePart"]));
            }
            set {
                this["multipleFileNamePart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\")]
        public string notAccessibleSubDirectory {
            get {
                return ((string)(this["notAccessibleSubDirectory"]));
            }
            set {
                this["notAccessibleSubDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pub")]
        public string properFileExtension {
            get {
                return ((string)(this["properFileExtension"]));
            }
            set {
                this["properFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qq")]
        public string unproperFileExtension {
            get {
                return ((string)(this["unproperFileExtension"]));
            }
            set {
                this["unproperFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("windows123")]
        public string singleFullFileName {
            get {
                return ((string)(this["singleFullFileName"]));
            }
            set {
                this["singleFullFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PromptForSomething")]
        public string promptMessage {
            get {
                return ((string)(this["promptMessage"]));
            }
            set {
                this["promptMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string defaultValue0_0 {
            get {
                return ((string)(this["defaultValue0_0"]));
            }
            set {
                this["defaultValue0_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.dwg")]
        public string fileNameWithPoint {
            get {
                return ((string)(this["fileNameWithPoint"]));
            }
            set {
                this["fileNameWithPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool trueTraverseSubDirectories {
            get {
                return ((bool)(this["trueTraverseSubDirectories"]));
            }
            set {
                this["trueTraverseSubDirectories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INTEL")]
        public string exactFileName {
            get {
                return ((string)(this["exactFileName"]));
            }
            set {
                this["exactFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6 ")]
        public string correctIntegerValue {
            get {
                return ((string)(this["correctIntegerValue"]));
            }
            set {
                this["correctIntegerValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\x1b")]
        public string ESCkeyUnicode {
            get {
                return ((string)(this["ESCkeyUnicode"]));
            }
            set {
                this["ESCkeyUnicode"] = value;
            }
        }
    }
}
